# Generated by Django 6.0 on 2026-02-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendee',
            name='role',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
