# Generated by Django 5.2.10 on 2026-02-10 17:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_fill_qr_tokens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
