# Generated by Django 6.0 on 2026-02-10 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_event_invited_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendee',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='attendee',
            constraint=models.UniqueConstraint(fields=('event', 'user'), name='unique_user_per_event'),
        ),
        migrations.AddConstraint(
            model_name='attendee',
            constraint=models.UniqueConstraint(fields=('event', 'name'), name='unique_name_per_event'),
        ),
    ]
